sonar.projectKey=sit753-devops-pipeline
sonar.projectName=SIT753 DevOps Pipeline
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
